name: CICD

on: push

jobs:

  Run-Python-Program:
    runs-on: ubuntu-latest
    
    steps:
  
      - name: Checkout Repo
        uses: actions@checkout@v3
      
      - name: Run Program
        run: python hello.py
    
