name: CICD

on: [push, workflow_dispatch]

jobs:

  Run-Python-Program:
  
    runs-on: ubuntu-latest
    
    steps:
  
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Run Program
        run: python hello.py
        
  Upload-Artifact:
    runs-on: ubuntu-latest
    needs: Run-Python-Program
    
    steps:
      
      - name: Checkout repo 2
        uses: actions/checkout@v3
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: .
          name: pooja
