name: Octo Organization CI

on: push

jobs:
  job1:
	  runs-on: ubuntu-latest
     
	  steps:
	    - name: step one
	      uses: actions/checkout@v3
        
	    - name: step 3
	      run: env
       
       




