name: jobs4_dependancy

on: push

jobs:
  job1:
    name: Ubuntu Machine
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: print date - ubuntu
        run: date
        
  job2:
    
    
    name: MacOS MAchine
    runs-on: macOS-latest
    
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: print date mac os
        run: date
        
  job3:

    name: Windows Machine
    runs-on: windows-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: print date on windows
        run: date
        
  job4:
    needs: [job1, job2, job3]
    name: ubuntu-20.04 Machine
    runs-on: ubuntu-20.04
    
    steps:
      - name: checkout ubuntu-20.04
        uses: actions/checkout@v2
        
      - name: Print date on ubuntu-20.04
        run: date
        
        
    
