name: jobs4_dependancy

on: push

jobs:
  job1:
    name: Ubuntu Machine
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: print date - ubuntu
        run: $date
    
