name: print_env_secrets

on: [push]

env:
  Workflow_level_variable: Workflow_Level
  overridden: WORKFLOW

jobs:

  print-env:
    runs-on: ubuntu-latest
    
    env: 
      Job_level_variable: Job_Level
      overridden: JOB
    
    steps:
    
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Print ENV
        run: |
          echo 1. Workflow_level_variable = ${{ env.Workflow_level_variable }}
          echo 2. Job_level_variable - ${{ env.Job_level_variable }}
          echo 3. overridden = ${{ env.overridden }}
        
    
  
    
    
