name: uploadArtifact_env

on: [push]

jobs:
  uploadArtifacts:
    runs-on: ubuntu-latest
    
    env: 
      artifact_name: uploaded_report
    
    steps:
      
     - name: Checkout The Code
     - uses: actions/checkout@v2
     
     - name: upload Artifacts
       uses: actions/upload-artifact@v3.1.2
       with:
        name: ${{ env.artifact_name }}
