name: uploadArtifact_env

on: [push]

jobs:
  uploadArtifacts:
    runs-on: ubuntu-latest
    
    env: 
      ARTIFACT_NAME: My_Report
    
    steps:
      
      - name: Checkout The Code
        uses: actions/checkout@v3

     
      - name: upload Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
